
services:
  pgvector:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: pgvector-db-lovable
    environment:
      POSTGRES_DB: Synth-account-db

      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "9010:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-lovable
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER:
      MINIO_ROOT_PASSWORD:
    ports:
      - "9000:9000"    # API
      - "9001:9001"    # Console
    volumes:
      - minio-data:/data
    restart: unless-stopped

  kafka:
    image: docker.io/confluentinc/cp-kafka:7.5.0
    container_name: kafka-lovable
    ports:
      - "9092:9092" # Internal/Docker port (if needed)
      - "29092:29092" # External port for your IDE/localhost
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'cl8A05wrTfuBtQWbUY_9fQ'
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped

volumes:
  minio-data:
  pgvector-data:
  kafka-data:
